// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCXOUZMVayRofvCBPA2qK-SlEI5WhfX9w',
    appId: '1:869002966506:web:c0eaa222ad27c7f534ee93',
    messagingSenderId: '869002966506',
    projectId: 'quickquoteapp-c3bfb',
    authDomain: 'quickquoteapp-c3bfb.firebaseapp.com',
    storageBucket: 'quickquoteapp-c3bfb.firebasestorage.app',
    measurementId: 'G-Y4RTBFLJNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCC0w5x9UPeXWoYPp-X1sEkFrwRz586wo',
    appId: '1:869002966506:android:050f3af9c453469134ee93',
    messagingSenderId: '869002966506',
    projectId: 'quickquoteapp-c3bfb',
    storageBucket: 'quickquoteapp-c3bfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdRg6Fvk9uCReGWwf_eBy3SHd0GA5oD7g',
    appId: '1:869002966506:ios:48d066fc9ef4019534ee93',
    messagingSenderId: '869002966506',
    projectId: 'quickquoteapp-c3bfb',
    storageBucket: 'quickquoteapp-c3bfb.firebasestorage.app',
    iosBundleId: 'com.example.quoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdRg6Fvk9uCReGWwf_eBy3SHd0GA5oD7g',
    appId: '1:869002966506:ios:48d066fc9ef4019534ee93',
    messagingSenderId: '869002966506',
    projectId: 'quickquoteapp-c3bfb',
    storageBucket: 'quickquoteapp-c3bfb.firebasestorage.app',
    iosBundleId: 'com.example.quoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCXOUZMVayRofvCBPA2qK-SlEI5WhfX9w',
    appId: '1:869002966506:web:87734f22b92579bd34ee93',
    messagingSenderId: '869002966506',
    projectId: 'quickquoteapp-c3bfb',
    authDomain: 'quickquoteapp-c3bfb.firebaseapp.com',
    storageBucket: 'quickquoteapp-c3bfb.firebasestorage.app',
    measurementId: 'G-B2CRBP4KDG',
  );
}
